"""
Java Class Templates
--------------------
Templates for generating complete Java source files.
"""

from .config import BridgeConfig


class JavaClassTemplate:
    """Generates the complete SpartanNative Java class."""

    HEADER = '''package {package};

import java.io.IOException;
import java.io.InputStream;
import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import org.jetbrains.annotations.NotNull;

/**
 * AUTOMATICALLY GENERATED - DO NOT EDIT.
 * Generated by scripts/generate_ffm_spartan_bridge.py
 *
 * Represents the low-level Foreign Function and Memory (FFM) bindings
 * for the Spartan Core Engine (C++26).
 */
public class {class_name} {{

    private static final String LIB_NAME = "{lib_name}";
    private static final Linker linker = Linker.nativeLinker();
    private static final SymbolLookup loader;

    // --- FFM Method Handles (declared before static block so they can be initialized there) ---
{handle_declarations}

    static {{
        loadNativeLibrary();
        loader = SymbolLookup.loaderLookup();

        // Initialize Native Method Handles (must not invoke any before all are bound)
{handle_initializations}

        // After all handles are bound, retrieve and cache the native layout signature
        // This ensures Java uses the authoritative native signature when available
{post_initialization}
    }}

    /**
     * Robust Native Library Loader.
     * Extracts shared library from JAR resources or falls back to system path.
     */
    private static void loadNativeLibrary() {{
        String osName = System.getProperty("os.name").toLowerCase();
        String libExtension;
        String libPrefix;

        if (osName.contains("win")) {{
            libExtension = ".dll";
            libPrefix = "";
        }} else if (osName.contains("mac")) {{
            libExtension = ".dylib";
            libPrefix = "lib";
        }} else {{
            libExtension = ".so";
            libPrefix = "lib";
        }}

        String libFileName = libPrefix + LIB_NAME + libExtension;
        String resourcePath = "/native/" + libFileName;

        try (InputStream is = {class_name}.class.getResourceAsStream(resourcePath)) {{
            if (is == null) {{
                System.loadLibrary(LIB_NAME);
                return;
            }}

            Path tempDir = Files.createTempDirectory("spartan-native");
            Path tempLib = tempDir.resolve(libFileName);
            Files.copy(is, tempLib, StandardCopyOption.REPLACE_EXISTING);
            tempLib.toFile().deleteOnExit();
            tempDir.toFile().deleteOnExit();

            System.load(tempLib.toAbsolutePath().toString());
        }} catch (IOException e) {{
            throw new RuntimeException("Failed to load native library: " + LIB_NAME, e);
        }}
     }}

     // --- Native API ---
{sync_methods}
}}
'''

    def __init__(self, config: BridgeConfig):
        self.config = config

    def render(
        self,
        handle_declarations: str,
        handle_initializations: str,
        sync_methods: str,
        post_initialization: str = ""
    ) -> str:
        """Render the complete Java class."""
        return self.HEADER.format(
            package=self.config.java_package,
            class_name=self.config.native_class_name,
            lib_name=self.config.lib_name,
            handle_declarations=handle_declarations,
            handle_initializations=handle_initializations,
            post_initialization=post_initialization,
            sync_methods=sync_methods
        )



