package org.spartan.internal.bridge;

import java.io.IOException;
import java.io.InputStream;
import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import org.jetbrains.annotations.NotNull;

/**
 * AUTOMATICALLY GENERATED - DO NOT EDIT.
 * Generated by scripts/generate_ffm_spartan_bridge.py
 *
 * Represents the low-level Foreign Function and Memory (FFM) bindings
 * for the Spartan Core Engine (C++26).
 */
public class SpartanNative {

    private static final String LIB_NAME = "spartan_core";
    private static final Linker linker = Linker.nativeLinker();
    private static final SymbolLookup loader;

    static {
        loadNativeLibrary();
        loader = SymbolLookup.loaderLookup();

        // Initialize Native Method Handles
        try {
            var addr = loader.find("spartan_init").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_init"));
            SPARTAN_INIT_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.ofVoid());
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_init", e);
        }
        try {
            var addr = loader.find("spartan_log").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_log"));
            SPARTAN_LOG_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_log", e);
        }
        try {
            var addr = loader.find("spartan_test_vector_union").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_test_vector_union"));
            SPARTAN_TEST_VECTOR_UNION_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_test_vector_union", e);
        }
        try {
            var addr = loader.find("spartan_register_model").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_register_model"));
            SPARTAN_REGISTER_MODEL_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_register_model", e);
        }
        try {
            var addr = loader.find("spartan_unregister_model").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_unregister_model"));
            SPARTAN_UNREGISTER_MODEL_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_unregister_model", e);
        }
        try {
            var addr = loader.find("spartan_proximal_policy_optimization_debug_get_scalar_count").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_proximal_policy_optimization_debug_get_scalar_count"));
            SPARTAN_PROXIMAL_POLICY_OPTIMIZATION_DEBUG_GET_SCALAR_COUNT_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_proximal_policy_optimization_debug_get_scalar_count", e);
        }
        try {
            var addr = loader.find("spartan_proximal_policy_optimization_debug_copy_scalars").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_proximal_policy_optimization_debug_copy_scalars"));
            SPARTAN_PROXIMAL_POLICY_OPTIMIZATION_DEBUG_COPY_SCALARS_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_proximal_policy_optimization_debug_copy_scalars", e);
        }
        try {
            var addr = loader.find("spartan_tick_all").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_tick_all"));
            SPARTAN_TICK_ALL_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_tick_all", e);
        }
        try {
            var addr = loader.find("updateContextPointer").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: updateContextPointer"));
            UPDATECONTEXTPOINTER_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: updateContextPointer", e);
        }
        try {
            var addr = loader.find("spartan_update_clean_sizes").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_update_clean_sizes"));
            SPARTAN_UPDATE_CLEAN_SIZES_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_update_clean_sizes", e);
        }
        try {
            var addr = loader.find("spartan_save_model").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_save_model"));
            SPARTAN_SAVE_MODEL_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_save_model", e);
        }
        try {
            var addr = loader.find("spartan_load_model").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_load_model"));
            SPARTAN_LOAD_MODEL_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_load_model", e);
        }
        try {
            var addr = loader.find("spartan_decay_exploration").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_decay_exploration"));
            SPARTAN_DECAY_EXPLORATION_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_decay_exploration", e);
        }
        try {
            var addr = loader.find("spartan_tick_agent").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_tick_agent"));
            SPARTAN_TICK_AGENT_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_DOUBLE));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_tick_agent", e);
        }
        try {
            var addr = loader.find("spartan_register_multi_agent").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_register_multi_agent"));
            SPARTAN_REGISTER_MULTI_AGENT_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_register_multi_agent", e);
        }
        try {
            var addr = loader.find("spartan_multi_agent_add_agent").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_multi_agent_add_agent"));
            SPARTAN_MULTI_AGENT_ADD_AGENT_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_multi_agent_add_agent", e);
        }
        try {
            var addr = loader.find("spartan_multi_agent_remove_agent").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_multi_agent_remove_agent"));
            SPARTAN_MULTI_AGENT_REMOVE_AGENT_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_multi_agent_remove_agent", e);
        }
        try {
            var addr = loader.find("spartan_tick_multi_agent").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_tick_multi_agent"));
            SPARTAN_TICK_MULTI_AGENT_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_tick_multi_agent", e);
        }
        try {
            var addr = loader.find("spartan_multi_agent_apply_rewards").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_multi_agent_apply_rewards"));
            SPARTAN_MULTI_AGENT_APPLY_REWARDS_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_multi_agent_apply_rewards", e);
        }
        try {
            var addr = loader.find("spartan_unregister_multi_agent").orElseThrow(() -> new RuntimeException("Native symbol resolution failed: spartan_unregister_multi_agent"));
            SPARTAN_UNREGISTER_MULTI_AGENT_HANDLE = linker.downcallHandle(addr, FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
        } catch (Exception e) {
            throw new RuntimeException("Failed to bind native function: spartan_unregister_multi_agent", e);
        }
    }

    /**
     * Robust Native Library Loader.
     * Extracts shared library from JAR resources or falls back to system path.
     */
    private static void loadNativeLibrary() {
        String osName = System.getProperty("os.name").toLowerCase();
        String libExtension;
        String libPrefix;

        if (osName.contains("win")) {
            libExtension = ".dll";
            libPrefix = "";
        } else if (osName.contains("mac")) {
            libExtension = ".dylib";
            libPrefix = "lib";
        } else {
            libExtension = ".so";
            libPrefix = "lib";
        }

        String libFileName = libPrefix + LIB_NAME + libExtension;
        String resourcePath = "/native/" + libFileName;

        try (InputStream is = SpartanNative.class.getResourceAsStream(resourcePath)) {
            if (is == null) {
                System.loadLibrary(LIB_NAME);
                return;
            }

            Path tempDir = Files.createTempDirectory("spartan-native");
            Path tempLib = tempDir.resolve(libFileName);
            Files.copy(is, tempLib, StandardCopyOption.REPLACE_EXISTING);
            tempLib.toFile().deleteOnExit();
            tempDir.toFile().deleteOnExit();

            System.load(tempLib.toAbsolutePath().toString());
        } catch (IOException e) {
            throw new RuntimeException("Failed to load native library: " + LIB_NAME, e);
        }
    }

    // --- FFM Method Handles ---
    private static final MethodHandle SPARTAN_INIT_HANDLE;
    private static final MethodHandle SPARTAN_LOG_HANDLE;
    private static final MethodHandle SPARTAN_TEST_VECTOR_UNION_HANDLE;
    private static final MethodHandle SPARTAN_REGISTER_MODEL_HANDLE;
    private static final MethodHandle SPARTAN_UNREGISTER_MODEL_HANDLE;
    private static final MethodHandle SPARTAN_PROXIMAL_POLICY_OPTIMIZATION_DEBUG_GET_SCALAR_COUNT_HANDLE;
    private static final MethodHandle SPARTAN_PROXIMAL_POLICY_OPTIMIZATION_DEBUG_COPY_SCALARS_HANDLE;
    private static final MethodHandle SPARTAN_TICK_ALL_HANDLE;
    private static final MethodHandle UPDATECONTEXTPOINTER_HANDLE;
    private static final MethodHandle SPARTAN_UPDATE_CLEAN_SIZES_HANDLE;
    private static final MethodHandle SPARTAN_SAVE_MODEL_HANDLE;
    private static final MethodHandle SPARTAN_LOAD_MODEL_HANDLE;
    private static final MethodHandle SPARTAN_DECAY_EXPLORATION_HANDLE;
    private static final MethodHandle SPARTAN_TICK_AGENT_HANDLE;
    private static final MethodHandle SPARTAN_REGISTER_MULTI_AGENT_HANDLE;
    private static final MethodHandle SPARTAN_MULTI_AGENT_ADD_AGENT_HANDLE;
    private static final MethodHandle SPARTAN_MULTI_AGENT_REMOVE_AGENT_HANDLE;
    private static final MethodHandle SPARTAN_TICK_MULTI_AGENT_HANDLE;
    private static final MethodHandle SPARTAN_MULTI_AGENT_APPLY_REWARDS_HANDLE;
    private static final MethodHandle SPARTAN_UNREGISTER_MULTI_AGENT_HANDLE;

    // --- Native API ---

    /**
     * Initializes the Spartan native engine.
     */
    public static void spartanInit() {
        try {
            SPARTAN_INIT_HANDLE.invokeExact();
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_init", t);
        }
    }

    /**
     * Logs a UTF-8 message through the Spartan console pipeline.
     */
    public static void spartanLog(@NotNull String message) {
        try (var arena = Arena.ofShared()) {
            var messageSegment = arena.allocateFrom(message);
            SPARTAN_LOG_HANDLE.invokeExact(messageSegment);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_log", t);
        }
    }

    /**
     * Computes the fuzzy-set union of two membership arrays in-place.
     */
    public static long spartanTestVectorUnion(@NotNull MemorySegment targetFuzzySet, @NotNull MemorySegment sourceFuzzySet, int targetSetSize, int sourceSetSize) {
        try {
            return (long) SPARTAN_TEST_VECTOR_UNION_HANDLE.invokeExact(targetFuzzySet, sourceFuzzySet, targetSetSize, sourceSetSize);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_test_vector_union", t);
        }
    }

    /**
     * Registers a new ML agent in the engine's model registry.
     */
    public static int spartanRegisterModel(long agentIdentifier, @NotNull MemorySegment opaqueHyperparameterConfig, @NotNull MemorySegment criticWeightsBuffer, int criticWeightsCount, @NotNull MemorySegment modelWeightsBuffer, int modelWeightsCount, @NotNull MemorySegment contextBuffer, int contextCount, @NotNull MemorySegment actionOutputBuffer, int actionOutputCount) {
        try {
            return (int) SPARTAN_REGISTER_MODEL_HANDLE.invokeExact(agentIdentifier, opaqueHyperparameterConfig, criticWeightsBuffer, criticWeightsCount, modelWeightsBuffer, modelWeightsCount, contextBuffer, contextCount, actionOutputBuffer, actionOutputCount);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_register_model", t);
        }
    }

    /**
     * Removes an agent from the registry (e.g., entity death / disconnect).
     */
    public static int spartanUnregisterModel(long agentIdentifier) {
        try {
            return (int) SPARTAN_UNREGISTER_MODEL_HANDLE.invokeExact(agentIdentifier);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_unregister_model", t);
        }
    }

    /**
     * Returns the number of scalar values exposed by the ProximalPolicyOptimization debug snapshot.
     */
    public static int spartanProximalPolicyOptimizationDebugGetScalarCount(long agentIdentifier) {
        try {
            return (int) SPARTAN_PROXIMAL_POLICY_OPTIMIZATION_DEBUG_GET_SCALAR_COUNT_HANDLE.invokeExact(agentIdentifier);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_proximal_policy_optimization_debug_get_scalar_count", t);
        }
    }

    /**
     * Copies a scalar debug snapshot from a ProximalPolicyOptimization model into a Java-owned buffer.
     */
    public static int spartanProximalPolicyOptimizationDebugCopyScalars(long agentIdentifier, @NotNull MemorySegment outputBuffer, int outputCount) {
        try {
            return (int) SPARTAN_PROXIMAL_POLICY_OPTIMIZATION_DEBUG_COPY_SCALARS_HANDLE.invokeExact(agentIdentifier, outputBuffer, outputCount);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_proximal_policy_optimization_debug_copy_scalars", t);
        }
    }

    /**
     * Executes a global engine tick across every registered agent.
     */
    public static int spartanTickAll(@NotNull MemorySegment agentIdentifiersBuffer, @NotNull MemorySegment rewardSignalsBuffer, int rewardEntryCount) {
        try {
            return (int) SPARTAN_TICK_ALL_HANDLE.invokeExact(agentIdentifiersBuffer, rewardSignalsBuffer, rewardEntryCount);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_tick_all", t);
        }
    }

    /**
     * Native binding for: updateContextPointer
     */
    public static void updateContextPointer(long agentIdentifier, @NotNull MemorySegment newPointer, int newCapacity) {
        try {
            UPDATECONTEXTPOINTER_HANDLE.invokeExact(agentIdentifier, newPointer, newCapacity);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: updateContextPointer", t);
        }
    }

    /**
     * Updates the clean sizes buffer for an active agent's variable-length context slices.
     */
    public static void spartanUpdateCleanSizes(long agentIdentifier, @NotNull MemorySegment cleanSizesBuffer, int slotCount) {
        try {
            SPARTAN_UPDATE_CLEAN_SIZES_HANDLE.invokeExact(agentIdentifier, cleanSizesBuffer, slotCount);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_update_clean_sizes", t);
        }
    }

    /**
     * Saves a model's complete state (model weights + critic weights) to a .spartan file.
     */
    public static int spartanSaveModel(long agentIdentifier, @NotNull String filePath, int modelTypeId) {
        try (var arena = Arena.ofShared()) {
            var filePathSegment = arena.allocateFrom(filePath);
            return (int) SPARTAN_SAVE_MODEL_HANDLE.invokeExact(agentIdentifier, filePathSegment, modelTypeId);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_save_model", t);
        }
    }

    /**
     * Loads model weights from a .spartan binary file into the given agent.
     */
    public static int spartanLoadModel(long agentIdentifier, @NotNull String filePath, int modelTypeId) {
        try (var arena = Arena.ofShared()) {
            var filePathSegment = arena.allocateFrom(filePath);
            return (int) SPARTAN_LOAD_MODEL_HANDLE.invokeExact(agentIdentifier, filePathSegment, modelTypeId);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_load_model", t);
        }
    }

    /**
     * Triggers exploration rate decay for a specific agent.
     */
    public static void spartanDecayExploration(long agentIdentifier) {
        try {
            SPARTAN_DECAY_EXPLORATION_HANDLE.invokeExact(agentIdentifier);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_decay_exploration", t);
        }
    }

    /**
     * Applies a reward and executes a single inference tick for one agent.
     */
    public static int spartanTickAgent(long agentIdentifier, double rewardSignal) {
        try {
            return (int) SPARTAN_TICK_AGENT_HANDLE.invokeExact(agentIdentifier, rewardSignal);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_tick_agent", t);
        }
    }

    /**
     * Registers a multi-agent group with the Spartan engine.
     */
    public static int spartanRegisterMultiAgent(long multiAgentId, @NotNull MemorySegment contextBuffer, int contextSize, @NotNull MemorySegment actionBuffer, int actionBufferSize, int actionFieldSize, int stateSize, int maxAgents) {
        try {
            return (int) SPARTAN_REGISTER_MULTI_AGENT_HANDLE.invokeExact(multiAgentId, contextBuffer, contextSize, actionBuffer, actionBufferSize, actionFieldSize, stateSize, maxAgents);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_register_multi_agent", t);
        }
    }

    /**
     * Adds an agent to an existing multi-agent group.
     */
    public static int spartanMultiAgentAddAgent(long multiAgentId, long agentIdentifier, @NotNull MemorySegment opaqueConfig, @NotNull MemorySegment modelWeights, int modelWeightsCount, @NotNull MemorySegment criticWeights, int criticWeightsCount) {
        try {
            return (int) SPARTAN_MULTI_AGENT_ADD_AGENT_HANDLE.invokeExact(multiAgentId, agentIdentifier, opaqueConfig, modelWeights, modelWeightsCount, criticWeights, criticWeightsCount);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_multi_agent_add_agent", t);
        }
    }

    /**
     * Removes an agent from a multi-agent group.
     */
    public static int spartanMultiAgentRemoveAgent(long multiAgentId, long agentIdentifier) {
        try {
            return (int) SPARTAN_MULTI_AGENT_REMOVE_AGENT_HANDLE.invokeExact(multiAgentId, agentIdentifier);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_multi_agent_remove_agent", t);
        }
    }

    /**
     * Executes a tick for all agents in a multi-agent group.
     */
    public static int spartanTickMultiAgent(long multiAgentId) {
        try {
            return (int) SPARTAN_TICK_MULTI_AGENT_HANDLE.invokeExact(multiAgentId);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_tick_multi_agent", t);
        }
    }

    /**
     * Applies rewards to all agents in a multi-agent group.
     */
    public static int spartanMultiAgentApplyRewards(long multiAgentId, @NotNull MemorySegment rewardsBuffer, int rewardCount) {
        try {
            return (int) SPARTAN_MULTI_AGENT_APPLY_REWARDS_HANDLE.invokeExact(multiAgentId, rewardsBuffer, rewardCount);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_multi_agent_apply_rewards", t);
        }
    }

    /**
     * Unregisters a multi-agent group from the engine.
     */
    public static int spartanUnregisterMultiAgent(long multiAgentId) {
        try {
            return (int) SPARTAN_UNREGISTER_MULTI_AGENT_HANDLE.invokeExact(multiAgentId);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_unregister_multi_agent", t);
        }
    }
}
