package org.spartan.internal.bridge;

import java.io.IOException;
import java.io.InputStream;
import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import org.jetbrains.annotations.NotNull;

/**
 * AUTOMATICALLY GENERATED - DO NOT EDIT.
 * Generated by scripts/generate_ffm_spartan_bridge.py
 *
 * Represents the low-level Foreign Function and Memory (FFM) bindings
 * for the Spartan Core Engine (C++26).
 */
public class SpartanNative {

    private static final String LIB_NAME = "spartan_core";
    private static final Linker linker = Linker.nativeLinker();
    private static final SymbolLookup loader;

    // --- FFM Method Handles (declared before static block so they can be initialized there) ---
    private static MethodHandle SPARTAN_INIT_HANDLE;
    private static MethodHandle SPARTAN_GET_LAYOUT_SIGNATURE_HANDLE;
    private static MethodHandle SPARTAN_LOG_HANDLE;
    private static MethodHandle SPARTAN_TEST_VECTOR_UNION_HANDLE;
    private static MethodHandle SPARTAN_REGISTER_MODEL_HANDLE;
    private static MethodHandle SPARTAN_UNREGISTER_MODEL_HANDLE;
    private static MethodHandle SPARTAN_PROXIMAL_POLICY_OPTIMIZATION_DEBUG_GET_SCALAR_COUNT_HANDLE;
    private static MethodHandle SPARTAN_PROXIMAL_POLICY_OPTIMIZATION_DEBUG_COPY_SCALARS_HANDLE;
    private static MethodHandle SPARTAN_TICK_ALL_HANDLE;
    private static MethodHandle UPDATECONTEXTPOINTER_HANDLE;
    private static MethodHandle SPARTAN_UPDATE_CLEAN_SIZES_HANDLE;
    private static MethodHandle SPARTAN_SAVE_MODEL_HANDLE;
    private static MethodHandle SPARTAN_LOAD_MODEL_HANDLE;
    private static MethodHandle SPARTAN_DECAY_EXPLORATION_HANDLE;
    private static MethodHandle SPARTAN_TICK_AGENT_HANDLE;
    private static MethodHandle SPARTAN_REGISTER_MULTI_AGENT_HANDLE;
    private static MethodHandle SPARTAN_MULTI_AGENT_ADD_AGENT_HANDLE;
    private static MethodHandle SPARTAN_MULTI_AGENT_REMOVE_AGENT_HANDLE;
    private static MethodHandle SPARTAN_TICK_MULTI_AGENT_HANDLE;
    private static MethodHandle SPARTAN_MULTI_AGENT_APPLY_REWARDS_HANDLE;
    private static MethodHandle SPARTAN_UNREGISTER_MULTI_AGENT_HANDLE;

    static {
        loadNativeLibrary();
        loader = SymbolLookup.loaderLookup();

        // Initialize Native Method Handles (must not invoke any before all are bound)
        var _opt_spartan_init = loader.find("spartan_init");
        if (_opt_spartan_init.isPresent()) {
            SPARTAN_INIT_HANDLE = linker.downcallHandle(_opt_spartan_init.get(), FunctionDescriptor.ofVoid());
        } else {
            SPARTAN_INIT_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_init");
        }
        var _opt_spartan_get_layout_signature = loader.find("spartan_get_layout_signature");
        if (_opt_spartan_get_layout_signature.isPresent()) {
            SPARTAN_GET_LAYOUT_SIGNATURE_HANDLE = linker.downcallHandle(_opt_spartan_get_layout_signature.get(), FunctionDescriptor.of(ValueLayout.JAVA_INT));
        } else {
            SPARTAN_GET_LAYOUT_SIGNATURE_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_get_layout_signature");
        }
        var _opt_spartan_log = loader.find("spartan_log");
        if (_opt_spartan_log.isPresent()) {
            SPARTAN_LOG_HANDLE = linker.downcallHandle(_opt_spartan_log.get(), FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
        } else {
            SPARTAN_LOG_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_log");
        }
        var _opt_spartan_test_vector_union = loader.find("spartan_test_vector_union");
        if (_opt_spartan_test_vector_union.isPresent()) {
            SPARTAN_TEST_VECTOR_UNION_HANDLE = linker.downcallHandle(_opt_spartan_test_vector_union.get(), FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
        } else {
            SPARTAN_TEST_VECTOR_UNION_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_test_vector_union");
        }
        var _opt_spartan_register_model = loader.find("spartan_register_model");
        if (_opt_spartan_register_model.isPresent()) {
            SPARTAN_REGISTER_MODEL_HANDLE = linker.downcallHandle(_opt_spartan_register_model.get(), FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } else {
            SPARTAN_REGISTER_MODEL_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_register_model");
        }
        var _opt_spartan_unregister_model = loader.find("spartan_unregister_model");
        if (_opt_spartan_unregister_model.isPresent()) {
            SPARTAN_UNREGISTER_MODEL_HANDLE = linker.downcallHandle(_opt_spartan_unregister_model.get(), FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
        } else {
            SPARTAN_UNREGISTER_MODEL_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_unregister_model");
        }
        var _opt_spartan_proximal_policy_optimization_debug_get_scalar_count = loader.find("spartan_proximal_policy_optimization_debug_get_scalar_count");
        if (_opt_spartan_proximal_policy_optimization_debug_get_scalar_count.isPresent()) {
            SPARTAN_PROXIMAL_POLICY_OPTIMIZATION_DEBUG_GET_SCALAR_COUNT_HANDLE = linker.downcallHandle(_opt_spartan_proximal_policy_optimization_debug_get_scalar_count.get(), FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
        } else {
            SPARTAN_PROXIMAL_POLICY_OPTIMIZATION_DEBUG_GET_SCALAR_COUNT_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_proximal_policy_optimization_debug_get_scalar_count");
        }
        var _opt_spartan_proximal_policy_optimization_debug_copy_scalars = loader.find("spartan_proximal_policy_optimization_debug_copy_scalars");
        if (_opt_spartan_proximal_policy_optimization_debug_copy_scalars.isPresent()) {
            SPARTAN_PROXIMAL_POLICY_OPTIMIZATION_DEBUG_COPY_SCALARS_HANDLE = linker.downcallHandle(_opt_spartan_proximal_policy_optimization_debug_copy_scalars.get(), FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } else {
            SPARTAN_PROXIMAL_POLICY_OPTIMIZATION_DEBUG_COPY_SCALARS_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_proximal_policy_optimization_debug_copy_scalars");
        }
        var _opt_spartan_tick_all = loader.find("spartan_tick_all");
        if (_opt_spartan_tick_all.isPresent()) {
            SPARTAN_TICK_ALL_HANDLE = linker.downcallHandle(_opt_spartan_tick_all.get(), FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } else {
            SPARTAN_TICK_ALL_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_tick_all");
        }
        var _opt_updateContextPointer = loader.find("updateContextPointer");
        if (_opt_updateContextPointer.isPresent()) {
            UPDATECONTEXTPOINTER_HANDLE = linker.downcallHandle(_opt_updateContextPointer.get(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } else {
            UPDATECONTEXTPOINTER_HANDLE = null;
            System.err.println("Warning: native symbol not found: updateContextPointer");
        }
        var _opt_spartan_update_clean_sizes = loader.find("spartan_update_clean_sizes");
        if (_opt_spartan_update_clean_sizes.isPresent()) {
            SPARTAN_UPDATE_CLEAN_SIZES_HANDLE = linker.downcallHandle(_opt_spartan_update_clean_sizes.get(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } else {
            SPARTAN_UPDATE_CLEAN_SIZES_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_update_clean_sizes");
        }
        var _opt_spartan_save_model = loader.find("spartan_save_model");
        if (_opt_spartan_save_model.isPresent()) {
            SPARTAN_SAVE_MODEL_HANDLE = linker.downcallHandle(_opt_spartan_save_model.get(), FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } else {
            SPARTAN_SAVE_MODEL_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_save_model");
        }
        var _opt_spartan_load_model = loader.find("spartan_load_model");
        if (_opt_spartan_load_model.isPresent()) {
            SPARTAN_LOAD_MODEL_HANDLE = linker.downcallHandle(_opt_spartan_load_model.get(), FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } else {
            SPARTAN_LOAD_MODEL_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_load_model");
        }
        var _opt_spartan_decay_exploration = loader.find("spartan_decay_exploration");
        if (_opt_spartan_decay_exploration.isPresent()) {
            SPARTAN_DECAY_EXPLORATION_HANDLE = linker.downcallHandle(_opt_spartan_decay_exploration.get(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));
        } else {
            SPARTAN_DECAY_EXPLORATION_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_decay_exploration");
        }
        var _opt_spartan_tick_agent = loader.find("spartan_tick_agent");
        if (_opt_spartan_tick_agent.isPresent()) {
            SPARTAN_TICK_AGENT_HANDLE = linker.downcallHandle(_opt_spartan_tick_agent.get(), FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_DOUBLE));
        } else {
            SPARTAN_TICK_AGENT_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_tick_agent");
        }
        var _opt_spartan_register_multi_agent = loader.find("spartan_register_multi_agent");
        if (_opt_spartan_register_multi_agent.isPresent()) {
            SPARTAN_REGISTER_MULTI_AGENT_HANDLE = linker.downcallHandle(_opt_spartan_register_multi_agent.get(), FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
        } else {
            SPARTAN_REGISTER_MULTI_AGENT_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_register_multi_agent");
        }
        var _opt_spartan_multi_agent_add_agent = loader.find("spartan_multi_agent_add_agent");
        if (_opt_spartan_multi_agent_add_agent.isPresent()) {
            SPARTAN_MULTI_AGENT_ADD_AGENT_HANDLE = linker.downcallHandle(_opt_spartan_multi_agent_add_agent.get(), FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } else {
            SPARTAN_MULTI_AGENT_ADD_AGENT_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_multi_agent_add_agent");
        }
        var _opt_spartan_multi_agent_remove_agent = loader.find("spartan_multi_agent_remove_agent");
        if (_opt_spartan_multi_agent_remove_agent.isPresent()) {
            SPARTAN_MULTI_AGENT_REMOVE_AGENT_HANDLE = linker.downcallHandle(_opt_spartan_multi_agent_remove_agent.get(), FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
        } else {
            SPARTAN_MULTI_AGENT_REMOVE_AGENT_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_multi_agent_remove_agent");
        }
        var _opt_spartan_tick_multi_agent = loader.find("spartan_tick_multi_agent");
        if (_opt_spartan_tick_multi_agent.isPresent()) {
            SPARTAN_TICK_MULTI_AGENT_HANDLE = linker.downcallHandle(_opt_spartan_tick_multi_agent.get(), FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
        } else {
            SPARTAN_TICK_MULTI_AGENT_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_tick_multi_agent");
        }
        var _opt_spartan_multi_agent_apply_rewards = loader.find("spartan_multi_agent_apply_rewards");
        if (_opt_spartan_multi_agent_apply_rewards.isPresent()) {
            SPARTAN_MULTI_AGENT_APPLY_REWARDS_HANDLE = linker.downcallHandle(_opt_spartan_multi_agent_apply_rewards.get(), FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
        } else {
            SPARTAN_MULTI_AGENT_APPLY_REWARDS_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_multi_agent_apply_rewards");
        }
        var _opt_spartan_unregister_multi_agent = loader.find("spartan_unregister_multi_agent");
        if (_opt_spartan_unregister_multi_agent.isPresent()) {
            SPARTAN_UNREGISTER_MULTI_AGENT_HANDLE = linker.downcallHandle(_opt_spartan_unregister_multi_agent.get(), FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
        } else {
            SPARTAN_UNREGISTER_MULTI_AGENT_HANDLE = null;
            System.err.println("Warning: native symbol not found: spartan_unregister_multi_agent");
        }

        // After all handles are bound, retrieve and cache the native layout signature
        // This ensures Java uses the authoritative native signature when available
try {
            if (SPARTAN_GET_LAYOUT_SIGNATURE_HANDLE != null) {
                int nativeSig = (int) SPARTAN_GET_LAYOUT_SIGNATURE_HANDLE.invokeExact();
                org.spartan.internal.engine.model.SpartanModelAllocator.setNativeLayoutSignature(nativeSig);
                System.out.println("[SpartanNative] Cached native layout signature: " + nativeSig);
            }
        } catch (Throwable t) {
            System.err.println("[SpartanNative] Warning: failed to retrieve native layout signature: " + t.getMessage());
        }
    }

    /**
     * Robust Native Library Loader.
     * Extracts shared library from JAR resources or falls back to system path.
     */
    private static void loadNativeLibrary() {
        String osName = System.getProperty("os.name").toLowerCase();
        String libExtension;
        String libPrefix;

        if (osName.contains("win")) {
            libExtension = ".dll";
            libPrefix = "";
        } else if (osName.contains("mac")) {
            libExtension = ".dylib";
            libPrefix = "lib";
        } else {
            libExtension = ".so";
            libPrefix = "lib";
        }

        String libFileName = libPrefix + LIB_NAME + libExtension;
        String resourcePath = "/native/" + libFileName;

        try (InputStream is = SpartanNative.class.getResourceAsStream(resourcePath)) {
            if (is == null) {
                System.loadLibrary(LIB_NAME);
                return;
            }

            Path tempDir = Files.createTempDirectory("spartan-native");
            Path tempLib = tempDir.resolve(libFileName);
            Files.copy(is, tempLib, StandardCopyOption.REPLACE_EXISTING);
            tempLib.toFile().deleteOnExit();
            tempDir.toFile().deleteOnExit();

            System.load(tempLib.toAbsolutePath().toString());
        } catch (IOException e) {
            throw new RuntimeException("Failed to load native library: " + LIB_NAME, e);
        }
     }

     // --- Native API ---

    /**
     * Initializes the Spartan native engine.
     */
    public static void spartanInit() {
        try {
            SPARTAN_INIT_HANDLE.invokeExact();
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_init", t);
        }
    }

    /**
     * Returns the computed layout signature for hyperparameter configs.
     */
    public static int spartanGetLayoutSignature() {
        if (SPARTAN_GET_LAYOUT_SIGNATURE_HANDLE == null) {
            return org.spartan.internal.engine.model.SpartanModelAllocator.getLayoutSignature();
        }
        try {
            return (int) SPARTAN_GET_LAYOUT_SIGNATURE_HANDLE.invokeExact();
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_get_layout_signature", t);
        }
    }

    /**
     * Logs a UTF-8 message through the Spartan console pipeline.
     */
    public static void spartanLog(@NotNull String message) {
        try (var arena = Arena.ofShared()) {
            var messageSegment = arena.allocateFrom(message);
            SPARTAN_LOG_HANDLE.invokeExact(messageSegment);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_log", t);
        }
    }

    /**
     * Computes the fuzzy-set union of two membership arrays in-place.
     */
    public static long spartanTestVectorUnion(@NotNull MemorySegment targetFuzzySet, @NotNull MemorySegment sourceFuzzySet, int targetSetSize, int sourceSetSize) {
        try {
            return (long) SPARTAN_TEST_VECTOR_UNION_HANDLE.invokeExact(targetFuzzySet, sourceFuzzySet, targetSetSize, sourceSetSize);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_test_vector_union", t);
        }
    }

    /**
     * Registers a new ML agent in the engine's model registry.
     */
    public static int spartanRegisterModel(long agentIdentifier, @NotNull MemorySegment opaqueHyperparameterConfig, @NotNull MemorySegment criticWeightsBuffer, int criticWeightsCount, @NotNull MemorySegment modelWeightsBuffer, int modelWeightsCount, @NotNull MemorySegment contextBuffer, int contextCount, @NotNull MemorySegment actionOutputBuffer, int actionOutputCount) {
        try {
            return (int) SPARTAN_REGISTER_MODEL_HANDLE.invokeExact(agentIdentifier, opaqueHyperparameterConfig, criticWeightsBuffer, criticWeightsCount, modelWeightsBuffer, modelWeightsCount, contextBuffer, contextCount, actionOutputBuffer, actionOutputCount);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_register_model", t);
        }
    }

    /**
     * Removes an agent from the registry (e.g., entity death / disconnect).
     */
    public static int spartanUnregisterModel(long agentIdentifier) {
        try {
            return (int) SPARTAN_UNREGISTER_MODEL_HANDLE.invokeExact(agentIdentifier);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_unregister_model", t);
        }
    }

    /**
     * Returns the number of scalar values exposed by the ProximalPolicyOptimization debug snapshot.
     */
    public static int spartanProximalPolicyOptimizationDebugGetScalarCount(long agentIdentifier) {
        try {
            return (int) SPARTAN_PROXIMAL_POLICY_OPTIMIZATION_DEBUG_GET_SCALAR_COUNT_HANDLE.invokeExact(agentIdentifier);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_proximal_policy_optimization_debug_get_scalar_count", t);
        }
    }

    /**
     * Copies a scalar debug snapshot from a ProximalPolicyOptimization model into a Java-owned buffer.
     */
    public static int spartanProximalPolicyOptimizationDebugCopyScalars(long agentIdentifier, @NotNull MemorySegment outputBuffer, int outputCount) {
        try {
            return (int) SPARTAN_PROXIMAL_POLICY_OPTIMIZATION_DEBUG_COPY_SCALARS_HANDLE.invokeExact(agentIdentifier, outputBuffer, outputCount);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_proximal_policy_optimization_debug_copy_scalars", t);
        }
    }

    /**
     * Executes a global engine tick across every registered agent.
     */
    public static int spartanTickAll(@NotNull MemorySegment agentIdentifiersBuffer, @NotNull MemorySegment rewardSignalsBuffer, int rewardEntryCount) {
        try {
            return (int) SPARTAN_TICK_ALL_HANDLE.invokeExact(agentIdentifiersBuffer, rewardSignalsBuffer, rewardEntryCount);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_tick_all", t);
        }
    }

    /**
     * Native binding for: updateContextPointer
     */
    public static void updateContextPointer(long agentIdentifier, @NotNull MemorySegment newPointer, int newCapacity) {
        try {
            UPDATECONTEXTPOINTER_HANDLE.invokeExact(agentIdentifier, newPointer, newCapacity);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: updateContextPointer", t);
        }
    }

    /**
     * Updates the clean sizes buffer for an active agent's variable-length context slices.
     */
    public static void spartanUpdateCleanSizes(long agentIdentifier, @NotNull MemorySegment cleanSizesBuffer, int slotCount) {
        try {
            SPARTAN_UPDATE_CLEAN_SIZES_HANDLE.invokeExact(agentIdentifier, cleanSizesBuffer, slotCount);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_update_clean_sizes", t);
        }
    }

    /**
     * Saves a model's complete state (model weights + critic weights) to a .spartan file.
     */
    public static int spartanSaveModel(long agentIdentifier, @NotNull String filePath, int modelTypeId) {
        try (var arena = Arena.ofShared()) {
            var filePathSegment = arena.allocateFrom(filePath);
            return (int) SPARTAN_SAVE_MODEL_HANDLE.invokeExact(agentIdentifier, filePathSegment, modelTypeId);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_save_model", t);
        }
    }

    /**
     * Loads model weights from a .spartan binary file into the given agent.
     */
    public static int spartanLoadModel(long agentIdentifier, @NotNull String filePath, int modelTypeId) {
        try (var arena = Arena.ofShared()) {
            var filePathSegment = arena.allocateFrom(filePath);
            return (int) SPARTAN_LOAD_MODEL_HANDLE.invokeExact(agentIdentifier, filePathSegment, modelTypeId);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_load_model", t);
        }
    }

    /**
     * Triggers exploration rate decay for a specific agent.
     */
    public static void spartanDecayExploration(long agentIdentifier) {
        try {
            SPARTAN_DECAY_EXPLORATION_HANDLE.invokeExact(agentIdentifier);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_decay_exploration", t);
        }
    }

    /**
     * Applies a reward and executes a single inference tick for one agent.
     */
    public static int spartanTickAgent(long agentIdentifier, double rewardSignal) {
        try {
            return (int) SPARTAN_TICK_AGENT_HANDLE.invokeExact(agentIdentifier, rewardSignal);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_tick_agent", t);
        }
    }

    /**
     * Registers a multi-agent group with the Spartan engine.
     */
    public static int spartanRegisterMultiAgent(long multiAgentId, @NotNull MemorySegment contextBuffer, int contextSize, @NotNull MemorySegment actionBuffer, int actionBufferSize, int actionFieldSize, int stateSize, int maxAgents) {
        try {
            return (int) SPARTAN_REGISTER_MULTI_AGENT_HANDLE.invokeExact(multiAgentId, contextBuffer, contextSize, actionBuffer, actionBufferSize, actionFieldSize, stateSize, maxAgents);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_register_multi_agent", t);
        }
    }

    /**
     * Adds an agent to an existing multi-agent group.
     */
    public static int spartanMultiAgentAddAgent(long multiAgentId, long agentIdentifier, @NotNull MemorySegment opaqueConfig, @NotNull MemorySegment modelWeights, int modelWeightsCount, @NotNull MemorySegment criticWeights, int criticWeightsCount) {
        try {
            return (int) SPARTAN_MULTI_AGENT_ADD_AGENT_HANDLE.invokeExact(multiAgentId, agentIdentifier, opaqueConfig, modelWeights, modelWeightsCount, criticWeights, criticWeightsCount);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_multi_agent_add_agent", t);
        }
    }

    /**
     * Removes an agent from a multi-agent group.
     */
    public static int spartanMultiAgentRemoveAgent(long multiAgentId, long agentIdentifier) {
        try {
            return (int) SPARTAN_MULTI_AGENT_REMOVE_AGENT_HANDLE.invokeExact(multiAgentId, agentIdentifier);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_multi_agent_remove_agent", t);
        }
    }

    /**
     * Executes a tick for all agents in a multi-agent group.
     */
    public static int spartanTickMultiAgent(long multiAgentId) {
        try {
            return (int) SPARTAN_TICK_MULTI_AGENT_HANDLE.invokeExact(multiAgentId);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_tick_multi_agent", t);
        }
    }

    /**
     * Applies rewards to all agents in a multi-agent group.
     */
    public static int spartanMultiAgentApplyRewards(long multiAgentId, @NotNull MemorySegment rewardsBuffer, int rewardCount) {
        try {
            return (int) SPARTAN_MULTI_AGENT_APPLY_REWARDS_HANDLE.invokeExact(multiAgentId, rewardsBuffer, rewardCount);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_multi_agent_apply_rewards", t);
        }
    }

    /**
     * Unregisters a multi-agent group from the engine.
     */
    public static int spartanUnregisterMultiAgent(long multiAgentId) {
        try {
            return (int) SPARTAN_UNREGISTER_MULTI_AGENT_HANDLE.invokeExact(multiAgentId);
        } catch (Throwable t) {
            throw new RuntimeException("Native invocation failed: spartan_unregister_multi_agent", t);
        }
    }
}
